### PR TITLE
Improve performance - stevengong

### PR DESCRIPTION
**Pull request by steven-g**

### CODE REVIEW

**Comment by steven-g** [comment]
https://people.sap.com/stevengong

**Comment by IObert** [comment]
Hi,
I tried to access your web app but it seems that the code is broken. You might want to check if you can fix this to get your points.
<https://steven-g.github.io/devtoberfest-2021-frontend-coding-challenge/>

**Comment by steven-g** [comment]
Due to the UI5 with "runtime cachebuster concept", the cachebuster is not working with local self-service server. I removed the cache buster function

**Comment by steven-g** [comment]
> Hi, I tried to access your web app but it seems that the code is broken. You might want to check if you can fix this to get your points. https://steven-g.github.io/devtoberfest-2021-frontend-coding-challenge/

Fixed.

**Comment by IObert** [comment]
Thanks a lot for your contribution. The solution looks great and I'll close this PR now!
You should receive your badge soon.

**Pull request closed without merging**
