### PR TITLE
Week 6 challenge

### PR DESCRIPTION
**Pull request by bmaciag**
very liked this type of challenge

### CODE REVIEW

**Comment by bmaciag** [comment]
https://people.sap.com/b.mac

**Comment by IObert** [comment]
Hi,
I'm glad you like this challenge and thanks for your contribution ✌️! 

I noticed that your GitHub Page is current exposing the wrong directory. It should expose the built web app (aka the `docs` folder) but it currently exposes the main readme file.
Can you please change this? In case you need help, please refer to the instructions in [this video](https://youtu.be/CBF_8eOjuc8?t=1651) or have a look at the [other pull requests](https://github.com/SAP-samples/devtoberfest-2021-frontend-coding-challenge/pulls?q=is%3Apr+is%3Aclosed).

**Comment by bmaciag** [comment]
> Hi, I'm glad you like this challenge and thanks for your contribution ✌️!
> 
> I noticed that your GitHub Page is current exposing the wrong directory. It should expose the built web app (aka the `docs` folder) but it currently exposes the main readme file. Can you please change this? In case you need help, please refer to the instructions in [this video](https://youtu.be/CBF_8eOjuc8?t=1651) or have a look at the [other pull requests](https://github.com/SAP-samples/devtoberfest-2021-frontend-coding-challenge/pulls?q=is%3Apr+is%3Aclosed).

Changed it to docs

**Comment by IObert** [comment]
Thanks, I see it now. Can you please push a new commit to retrigger the GitHub Action that assess your PR? From looking at your code, it could be that the score is below 75 (but maybe you are lucky :) )

**Comment by bmaciag** [comment]
My chrome says 94% ;)
Did the new commit.

**Comment by bmaciag** [comment]
https://people.sap.com/b.mac

**Comment by bmaciag** [comment]
https://people.sap.com/b.mac

**Comment by IObert** [comment]
Thanks a lot for your contribution. The solution looks great and I'll close this PR now!
You should receive your badge soon.

**Pull request closed without merging**
