### PR TITLE
optimization1_as.karpov1

### PR DESCRIPTION
**Pull request by karpovas1505**

### CODE REVIEW

**Comment by karpovas1505** [comment]
How i can agree with CLA?

**Comment by IObert** [comment]
You can ignore the CLA as we won't merge the PR anyway :)

**Comment by karpovas1505** [comment]
This is my profile
https://people.sap.com/as.karpov1

**Comment by karpovas1505** [comment]
> You can ignore the CLA as we won't merge the PR anyway :)

thanks, Marius

**Comment by karpovas1505** [comment]
> Congrats 🥳, your web app achieved a performace score of 73. Great job 💪!
> 
> So that we can [recognize your solution for the coding challenge](https://github.com/SAP-samples/devtoberfest-2021/blob/main/topics/Week6_Frontend/README.md#coding-challenge), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> https://people.sap.com/your-user-name
> 
> Thanks!

https://people.sap.com/as.karpov1

**Comment by IObert** [comment]
I got a quick question. I can see your web app here <https://karpovas1505.github.io/devtoberfest-2021-frontend-coding-challenge/> and there is a comment from the GitHub Bot but I don't see any completed "Checks" in the PR.
This surprises me. Can you please double-check that you activated "GitHub Actions" in your repo as instructed [in the video](https://youtu.be/CBF_8eOjuc8?t=1685)?

**Comment by karpovas1505** [comment]
Yes,  it is activated. Such as in video.

вт, 9 нояб. 2021 г., 18:41 Marius Obert ***@***.***>:

**Comment by karpovas1505** [comment]
> I got a quick question. I can see your web app here https://karpovas1505.github.io/devtoberfest-2021-frontend-coding-challenge/ and there is a comment from the GitHub Bot but I don't see any completed "Checks" in the PR. This surprises me. Can you please double-check that you activated "GitHub Actions" in your repo as instructed [in the video](https://youtu.be/CBF_8eOjuc8?t=1685)?

Снимок

**Comment by karpovas1505** [comment]
> > I got a quick question. I can see your web app here https://karpovas1505.github.io/devtoberfest-2021-frontend-coding-challenge/ and there is a comment from the GitHub Bot but I don't see any completed "Checks" in the PR. This surprises me. Can you please double-check that you activated "GitHub Actions" in your repo as instructed [in the video](https://youtu.be/CBF_8eOjuc8?t=1685)?
> 
> Снимок

**Comment by IObert** [comment]
Weird. Anyway, you should have received your badge. 
Thanks a lot for contributing!

**Pull request closed without merging**
