### PR TITLE
Submission for Code Challenge - fabien_henique

### PR DESCRIPTION
**Pull request by FabienHenique**

### CODE REVIEW

**Comment by FabienHenique** [comment]
https://people.sap.com/fabien_henique

**Comment by IObert** [comment]
Hi,
I'm glad you like this challenge and thanks for your contribution ✌️! 

I noticed that your GitHub Page is current exposing the wrong directory. It should expose the built web app (aka the `docs` folder) but it currently exposes the main readme file.
Can you please change this? In case you need help, please refer to the instructions in [this video](https://youtu.be/CBF_8eOjuc8?t=1651) or have a look at the [other pull requests](https://github.com/SAP-samples/devtoberfest-2021-frontend-coding-challenge/pulls?q=is%3Apr+is%3Aclosed).

**Comment by FabienHenique** [comment]
Hello @IObert, 

It should be good now!
My GitHub [page ](https://fabienhenique.github.io/devtoberfest-2021-frontend-coding-challenge/)is showing the webapp and not readme :)

Thanks again for your support and for this challenge.

**Comment by IObert** [comment]
Thanks a lot for your contribution. The solution looks great and I'll close this PR now!
You should receive your badge soon.

**Pull request closed without merging**
